SOURCES=thtranscode.ml
RESULT=thtranscode
OCAMLOGG_DIR=../../ocaml-ogg/src
INCDIRS=../src $(OCAMLOGG_DIR)
LIBS=unix bigarray ogg theora
ANNOTATE = true

all: nc

test: all
	./thencode

include OCamlMakefile
